### PR TITLE
Update userscript.js actionsButtons and activityPanel

### PR DESCRIPTION
**Pull request by Mini-Gaunt**
Update for discord web changes, fixes issue with start stream button.

### CODE REVIEW

**Comment by MrakDun-desu** [comment]
Tried to build this with Debian 12, audio sharing works now, but after the change the video doesn't work instead, possibly because of outdated Debian libraries.

The main start stream button in the middle of the screen still doesn't work though, only the small one on the bottom left.

**Comment by Mini-Gaunt** [comment]
> Tried to build this with Debian 12, audio sharing works now, but after the change the video doesn't work instead, possibly because of outdated Debian libraries.
> 
> The main start stream button in the middle of the screen still doesn't work though, only the small one on the bottom left.

I think the start stream button in the center is supposed to be grayed out, at least according to the most recent commit. I will take a quick look to see if that is also a quick fix

**Comment by maltejur** [comment]
Thanks for the fix, I'll do another release with it.

**Comment by sumeet** [comment]
i tried this fix, and it looks like the screensharing and audio work, but changing the video quality settings don't actually take effect. seems to be set to 720 / 30fps no matter what i select.

**Pull request merged**
