### PR TITLE
Move two functions into separate file

### PR DESCRIPTION
**Pull request by Vitalya-code**
I noticed that something can call every function in the main file, including my new functions. To prevent this from happening, the easiest solution would be to move these functions to a separate file. After making this change, everything seems to be fine.

### CODE REVIEW

**Comment by Vitalya-code** [comment]
But now you can open two instances...
Don't merge it now

**Comment by Vitalya-code** [comment]
Do you have any ideas how to fix it?

**Comment by Vitalya-code** [comment]
Ok, the bug is gone for now. You can merge

**Comment by maltejur** [comment]
Thanks once again, looking good

**Pull request merged**
